# Video "What is TensorFlow"

This notebook was implemented by coursera, i just cometed a fell rows for my understanding.

In [5]:
%config IPCompleter.greedy=True

In [6]:
import tensorflow as tf
import numpy as np
print(tf.__version__)

1.2.1


In [7]:
# Clean the jupyter notebook stdout 
tf.reset_default_graph()

# Create a placeholder variable for to fed in sequence
a = tf.placeholder(np.float32, (2, 2))

# Crate a variable for to update in sequece
b = tf.Variable(tf.ones((2, 2)))
c = a @ b

In [9]:
# Print tensor object
print(c)

Tensor("matmul:0", shape=(2, 2), dtype=float32)


In [10]:
# Run tensorflow section for to execute calculus
s = tf.InteractiveSession()

In [11]:
# Put tensor variable in session tensorflow
s.run(tf.global_variables_initializer())

# Execute calculus in running session
s.run(c, feed_dict={a: np.ones((2, 2))})

array([[ 2.,  2.],
       [ 2.,  2.]], dtype=float32)

In [12]:
s.close()

# Video "Our first model in TensorFlow"

### Simple optimization (with simple prints)

In [13]:
tf.reset_default_graph()

# This way you can create a variable too and execute in numpy operation
x = tf.get_variable("x", shape=(), dtype=tf.float32, trainable=True)
f = x ** 2

In [14]:
# Here the tf.train for get a GradientDescentOptimizer for to find the minimum in f(x) = x²
optimizer = tf.train.GradientDescentOptimizer(0.1)
step = optimizer.minimize(f, var_list=[x])

In [15]:
# Show the variables in RAM
tf.trainable_variables()

[<tf.Variable 'x:0' shape=() dtype=float32_ref>]

In [17]:
# Execute a tensorflow run for to find the minimum in x² function, look here, beacuse we have a
# problem why don't sicronize in f and x
with tf.Session() as s:  # in this way session will be closed automatically
    s.run(tf.global_variables_initializer())
    for i in range(10):
        _, curr_x, curr_f = s.run([step, x, f])
        print(curr_x, curr_f)

-1.16563 2.12297
-0.932507 1.3587
-0.746006 0.869569
-0.596804 0.556524
-0.477444 0.356176
-0.381955 0.227952
-0.305564 0.14589
-0.244451 0.0933693
-0.195561 0.0597563
-0.156449 0.0382441


### Simple optimization (with tf.Print)

In [18]:
# Use tg.Print for to get a sincronize and print results
tf.reset_default_graph()
x = tf.get_variable("x", shape=(), dtype=tf.float32)
f = x ** 2
f = tf.Print(f, [x, f], "x, f:")

In [19]:
optimizer = tf.train.GradientDescentOptimizer(0.1)
step = optimizer.minimize(f)

In [20]:
with tf.Session() as s:
    s.run(tf.global_variables_initializer())
    for i in range(10):
        s.run([step, f])

In [15]:
# Prints to jupyter server stdout (not available in Coursera Notebooks):
# 2018-07-21 18:01:27.308270: I tensorflow/core/kernels/logging_ops.cc:79] x, f:[-1.0670249][1.1385423]
# 2018-07-21 18:01:27.308809: I tensorflow/core/kernels/logging_ops.cc:79] x, f:[-0.85361993][0.72866696]
# 2018-07-21 18:01:27.309116: I tensorflow/core/kernels/logging_ops.cc:79] x, f:[-0.68289596][0.46634689]
# 2018-07-21 18:01:27.309388: I tensorflow/core/kernels/logging_ops.cc:79] x, f:[-0.54631674][0.29846197]
# 2018-07-21 18:01:27.309678: I tensorflow/core/kernels/logging_ops.cc:79] x, f:[-0.43705338][0.19101566]
# 2018-07-21 18:01:27.309889: I tensorflow/core/kernels/logging_ops.cc:79] x, f:[-0.34964269][0.12225001]
# 2018-07-21 18:01:27.310213: I tensorflow/core/kernels/logging_ops.cc:79] x, f:[-0.27971417][0.078240015]
# 2018-07-21 18:01:27.310475: I tensorflow/core/kernels/logging_ops.cc:79] x, f:[-0.22377133][0.050073609]
# 2018-07-21 18:01:27.310751: I tensorflow/core/kernels/logging_ops.cc:79] x, f:[-0.17901707][0.032047112]
# 2018-07-21 18:01:27.310963: I tensorflow/core/kernels/logging_ops.cc:79] x, f:[-0.14321366][0.020510152]

### Simple optimization (with TensorBoard logging)

In [21]:
# In this way you can view the results in a Board by tensorflow API, the TensorBoard. You can view the results and
# computational grafhs
tf.reset_default_graph()
x = tf.get_variable("x", shape=(), dtype=tf.float32)
f = x ** 2

In [22]:
optimizer = tf.train.GradientDescentOptimizer(0.1)
step = optimizer.minimize(f)

In [23]:
tf.summary.scalar('curr_x', x)
tf.summary.scalar('curr_f', f)
summaries = tf.summary.merge_all()

In [24]:
s = tf.InteractiveSession()
summary_writer = tf.summary.FileWriter("logs/1", s.graph)
s.run(tf.global_variables_initializer())
for i in range(10):
    _, curr_summaries = s.run([step, summaries])
    summary_writer.add_summary(curr_summaries, i)
    summary_writer.flush()

Run  `tensorboard --logdir=./logs` in bash

This is what you can see in your browser **(not available in Coursera Notebooks)**
<img src="images/TensorBoard.jpg" style="width:70%">

**If you're running on Google Colab you can still run TensorBoard!**

In [25]:
# !!! RUN THIS CELL ONLY ON GOOGLE COLAB !!!
! wget https://raw.githubusercontent.com/hse-aml/intro-to-dl/master/setup_google_colab.py -O setup_google_colab.py
import setup_google_colab

# run tensorboard in background
import os
os.system("tensorboard --logdir=./logs --host 0.0.0.0 --port 6006 &")

# expose port and show the link
setup_google_colab.expose_port_on_colab(6006)

--2021-02-14 20:56:42--  https://raw.githubusercontent.com/hse-aml/intro-to-dl/master/setup_google_colab.py
Resolving proxy-coursera-apps.org (proxy-coursera-apps.org)... 10.0.0.170
Connecting to proxy-coursera-apps.org (proxy-coursera-apps.org)|10.0.0.170|:3128... connected.
Proxy request sent, awaiting response... 200 OK
Length: 3636 (3.6K) [text/plain]
Saving to: ‘setup_google_colab.py’

setup_google_colab. 100%[===================>]   3.55K  --.-KB/s    in 0s      

2021-02-14 20:56:42 (89.2 MB/s) - ‘setup_google_colab.py’ saved [3636/3636]



CalledProcessError: Command 'netstat -vatn' returned non-zero exit status 127.

In [20]:
s.close()

### Training a linear model

In [26]:
# generate model data
N = 1000
D = 3
x = np.random.random((N, D))
w = np.random.random((D, 1))
y = x @ w + np.random.randn(N, 1) * 0.20

print(x.shape, y.shape)
print(w.T)

(1000, 3) (1000, 1)
[[ 0.98542123  0.95468443  0.43104563]]


In [27]:
tf.reset_default_graph()

features = tf.placeholder(tf.float32, shape=(None, D))
target = tf.placeholder(tf.float32, shape=(None, 1))

weights = tf.get_variable("weights", shape=(D, 1), dtype=tf.float32)
predictions = features @ weights

loss = tf.reduce_mean((target - predictions) ** 2)

print(target.shape, predictions.shape, loss.shape)

(?, 1) (?, 1) ()


In [28]:
optimizer = tf.train.GradientDescentOptimizer(0.1)
step = optimizer.minimize(loss)

In [29]:
with tf.Session() as s:
    s.run(tf.global_variables_initializer())
    for i in range(300):
        _, curr_loss, curr_weights = s.run([step, loss, weights], 
                                           feed_dict={features: x, target: y})
        if i % 50 == 0:
            print(curr_loss)

0.659815
0.0642267
0.0460101
0.0427283
0.042136
0.0420289


In [30]:
# found weights
curr_weights.T

array([[ 1.00481117,  0.94985271,  0.41648892]], dtype=float32)

In [31]:
# true weights
w.T

array([[ 0.98542123,  0.95468443,  0.43104563]])